version: 0.2

phases:
    install:
        on-failure: ABORT
        commands:
            - echo "Installing Dependencies..." 
            - npm i
    pre_build:
        commands:
            - echo "Auditing and fixing vulnerabilities..."
            - npm audit fix
    build:
        commands:
            - echo "Zipping deployment package..."
            - zip -r artifact.zip *
    post_build:
        commands:
            - echo "Updating Lambda Function..."
            - aws lambda update-function-code --function-name brekrr-common-microservice-$env_type --zip-file fileb://artifact.zip

artifacts:
    files:
        - '**/*'
    name: artifact